- hosts: all
  gather_facts: no
  tasks:
  - name: Install python
    raw: "apt update && apt install -y python"

- hosts: all
  roles:
  - SoInteractive.docker

- hosts: influxdb
  tasks:
  - name: Start infludb container
    command: docker run -d --name influx -p 8086:8086 --mount type=tmpfs,tmpfs-size=209715200,destination=/var/lib/influxdb influxdb:1.4.3-alpine
    # docker_container doesn't support 
    #docker_container:
    #  name: influx
    #  image: influxdb:1.4.3-alpine
    #  state: started
    #  ports:
    #    - 8086:8086
  - name: Create crontab entry to restart influxdb
    become: yes
    cron:
      cron_file: /etc/crontab
      name: InfluxDB retention
      job: >
        docker rm -f influx; 
        docker run -d --name influx -p 8086:8086 --mount type=tmpfs,tmpfs-size=209715200,destination=/var/lib/influxdb influxdb:1.4.3-alpine
      user: root

- hosts: web
  roles:
  - antoiner77.caddy
  pre_tasks:
  - name: Ensure webdirs exists
    file:
      path: /var/www/img
      state: directory
  - name: Ensure portal site exists
    copy:
      src: index.html
      dest: /var/www/index.html
  - name: Copy images
    copy:
      src: "img/{{ item }}"
      dest: "/var/www/img/{{ item }}"
    with_items:
    - logo.png
    - digitalocean.png
  vars:
    caddy_systemd_capabilities_enabled: True
    caddy_features: http.prometheus
    caddy_config: |
      "{{ ansible_host }}"
      prometheus
      tls paulfantom@gmail.com
      ext .html
      root /var/www

