- hosts: all
  gather_facts: no
  tasks:
  - name: Install python
    raw: "apt update && apt install -y python"

- hosts: all
  roles:
  - SoInteractive.docker

- name: Configure persistent data store
  hosts: influxdb
  tasks:
  - name: Retain influxdb container
    docker_container:
      name: influx
      state: absent
    when: ansible_date_time.day == "01"
  - name: Retain influxdb data
    docker_volume:
      name: influxdb
      state: absent
    when: ansible_date_time.day == "01"
  - name: Ensure influxdb bave a place to store data
    docker_volume:
      name: influxdb
      state: present
  - name: Start influxdb container
    docker_container:
      name: influx
      image: influxdb:alpine
      state: present
      ports:
        - "8086:8086"
      volumes:
        - "influxdb:/var/lib/influxdb"
      env:
        INFLUXDB_HTTP_AUTH_ENABLED: "true"
        INFLUXDB_ADMIN_USER: "{{ influxdb_user }}"
        INFLUXDB_ADMIN_PASSWORD: "{{ influxdb_password }}"
        INFLUXDB_DB: "{{ influxdb_db }}"

- hosts: web
  roles:
  - antoiner77.caddy
  pre_tasks:
  - name: Ensure webdirs exists
    file:
      path: /var/www/img
      state: directory
  - name: Ensure portal site exists
    copy:
      src: index.html
      dest: /var/www/index.html
  - name: Copy images
    copy:
      src: "img/{{ item }}"
      dest: "/var/www/img/{{ item }}"
    with_items:
    - logo.png
    - digitalocean.png
  vars:
    caddy_systemd_capabilities_enabled: True
    caddy_features: http.prometheus
    caddy_config: |
      "{{ ansible_host }}"
      prometheus
      tls paulfantom@gmail.com
      ext .html
      root /var/www

