- hosts: all
  gather_facts: no
  tasks:
  - name: Install python
    raw: "apt update && apt install -y python"

- hosts: all
  roles:
  - SoInteractive.docker

- hosts: web
  roles:
  - antoiner77.caddy
  pre_tasks:
  - name: Ensure webdirs exists
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /var/www/demo
      - /var/www/demo/img
      - /var/www/presentation
  - name: Ensure portal site exists
    copy:
      src: index.html
      dest: /var/www/demo/index.html
  - name: Copy images
    copy:
      src: "img/{{ item }}"
      dest: "/var/www/demo/img/{{ item }}"
    with_items:
    - logo.png
    - digitalocean.png
  vars:
    caddy_systemd_capabilities_enabled: True
    caddy_features: http.prometheus
    caddy_config: |
      {{ ansible_host }} {
        ext .html
        root /var/www/demo/
        prometheus
        tls paulfantom@gmail.com
      }
      presentation.cloudalchemy.org {
        root /var/www/presentation
        tls paulfantom@gmail.com
      }
