- hosts: all
  gather_facts: no
  tasks:
  - name: Install python
    raw: "apt update && apt install -y python"

- hosts: all
  roles:
    - cloudalchemy.node-exporter
    - cloudalchemy.prometheus
    - cloudalchemy.alertmanager
    - cloudalchemy.grafana
